spring.application.name=petstay-api

# Conexão com o Banco
spring.datasource.url=jdbc:postgresql://localhost:5432/petstay
spring.datasource.username=user
spring.datasource.password=password

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret (Necessário para a parte de segurança depois)
api.security.token.secret=minha-chave-secreta-super-segura-petstay-2026
